// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClqtDahfZHROSTomyc0PeQ9U2tbqqAqaU',
    appId: '1:422378501256:web:47c742e650ee36947c5b3d',
    messagingSenderId: '422378501256',
    projectId: 'pdp-bazar-home',
    authDomain: 'pdp-bazar-home.firebaseapp.com',
    storageBucket: 'pdp-bazar-home.appspot.com',
    measurementId: 'G-JG3413S6E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXV7o18UEgnpmfirOPa0_xWzKNqOIOFZA',
    appId: '1:422378501256:android:fb81a7f8b94da9027c5b3d',
    messagingSenderId: '422378501256',
    projectId: 'pdp-bazar-home',
    storageBucket: 'pdp-bazar-home.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNDZB6BGzbszozr7EwftyFp0CHvTKqxXk',
    appId: '1:422378501256:ios:818c5a00e793834b7c5b3d',
    messagingSenderId: '422378501256',
    projectId: 'pdp-bazar-home',
    storageBucket: 'pdp-bazar-home.appspot.com',
    iosClientId: '422378501256-9ib89mb8kt7jag5v916nqaq5lpas6vih.apps.googleusercontent.com',
    iosBundleId: 'com.alix.pdpBazarHome',
  );
}
